### ISSUE TITLE
Dupla Andre_Thayssa: Proposta de Projeto Final - Artigo

### ISSUE THREAD

**Issue by ThayssaRocha** [gustavopinto/tesl#148]
A proposta do nosso trabalho final consiste num artigo que considera a hipótese de que todos os projetos de software livre possuem algum processo (ainda que mínimo) para desenvolvimento de software, que cresce em complexidade conforme a robustez e especialmente a existência de patrocinadores. 
Este processo consiste nas regras para contribuição, definidas nas regras explicitas em cada projeto, incluindo também pré-condições de uso de padrões de projeto e envio de classes de teste juntamente com a implementação realizada.
Desta forma, se torna possível a avaliação do processo de um projeto de software livre utilizando modelos de referência como CMMI, por exemplo.
Neste artigo, propomos realizar a avaliação do processo de desenvolvimento do KDE-Plasma para as áreas de processo do CMMI que definem modelo de referência da categoria "engenharia":  Product Integration (PI), Requirements Development (RD),  Technical Solution (TS) ,  Validation (VAL) ,  Verification (VER).
Desta forma, será possível identificar o grau de aderência do processo de desenvolvimento do KDE-Plasma contra o modelo proposto pelo CMMI-Dev 1.3 .

**Comment by gustavopinto** [comment]
Parece interessante, mas como seria feito a avaliação desse trabalho, @ThayssaRocha? Por favor, cole aqui tbm a estrutura do artigo.

**Comment by ThayssaRocha** [comment]
Pensei nesse formato aqui... daria pra avaliar o processo do KDE-Plasma contra as práticas descritas nos processos do CMMI... como se fosse uma avaliação de processo mesmo. Daria pra avaliar a aderência.

1.	Introdução
2.	Software Livre
	- Conceituação de software livre
3.	Engenharia de Software
	- Conceituação de engenharia de software
4.	O paradoxo do Processo de Desenvolvimento – Software Livre x Software Proprietário
	- Abordagem do livro catedral x bazar
	- Modelos de referência p/ processo de desenv software proprietário/empresarial
	- Processos ágeis (talvez)
	- Processos que existem em projetos de software livre atualmente
5.	KDE – Plasma: um projeto de software livre
	- Apresentação do projeto KDE Plasma e seu processo
6.	CMMI: um modelo de referência para processos de desenvolvimento de software
	- Apresentação modelo de referência: detalhamento dos processos de engenharia Product Integration (PI), Requirements Development (RD), Technical Solution (TS) , Validation (VAL) , Verification (VER).
7.	Avaliando o processo de desenvolvimento do KDE-Plasma
	- Realização da avaliação do processo de desenvolvimento do KDE-Plasma contra os processos de engenheria (PI, RD, TS, VAL, VER)
8.	Conclusões

**Comment by gustavopinto** [comment]
Olá, @ThayssaRocha, 

como a proposta é criar um artigo científico, sugiro que a estrutura seja adaptada para algo do tipo:

1. Introdução (aqui deve estar a parte do paradoxo do processo de desenvolvimento
2. Fundamentação Teórica (falar dos itens fundamentais do seu trabalho)
3. Método (como os dados foram coletados e organizados?)
4. Resultados (discussão das abordagens? apresentação da avaliação)
5. Trabalhos relacionados
6. Conclusão

**Comment by gustavopinto** [comment]
Mais importante nesse momento, porém, é a metodologia. Que tipo de dados vc quer coletar e como vc pretende fazer isso?

**Comment by ThayssaRocha** [comment]
Perfeita a estrutura! O Sandro tinha me dado uma sugestão tb semelhante. Peço desculpas pela demora no retorno, pois eu estava organizando um evento que finalmente já aconteceu e agora posso me dedicar só pro artigo. Dentro da estrutura proposta, penso que a metodologia seria a realização de um estudo de caso, observando (e desenhando) o processo de um grande projeto de SL (KDI Plasma) e aplicando uma avaliação CMMI para obter o grau de aderência deste processo com relação aos processos avaliados (a proposta é avaliar os 5 do grupo engenharia) o que vai gerar um dado quantitativo de % de aderência, podendo o valor obtido corroborar com a hipótese de que estes processos também precisam apresentar algum nível de rigor para garantir o bom funcionamento do projeto.

**Comment by filipesaraiva** [comment]
@ThayssaRocha em https://github.com/gustavopinto/tesl/issues/148#issuecomment-505232577:

> (...)o processo de um grande projeto de SL (KDI Plasma) (...)

Não é KDI, Thayssa :man_facepalming: :rofl:

**Comment by gustavopinto** [comment]
Oi @ThayssaRocha: acho que seria um interessante estudo observacional. Mas, antes de qualquer coisa: você já sabe como e onde seria feito essa observação? Listas de email? Issues? Wikis? Seria bom poder definir melhor esses pontos pra poder seguir em frente.

**Comment by ThayssaRocha** [comment]
Gustavo, a observação será feita nos próprios sites dos projetos, que descrevem de maneira textual os processos. Basicamente naquelas "orientações para contribuidores". Já andei olhando no KDE (viu @filipesaraiva acertei agora!) e penso que posso achar em outro projeto relevante tb (manda uma sugestão!). De repente, a gente podia reduzir o escopo do artigo pelo avançado do prazo e focar em apenas um processo do CMMI, por exemplo, no processo de verificação (VER) que são geralmente muito bem descritos, como podemos ver neste aqui da comunidade KDE: https://community.kde.org/Get_Involved/Bug_Reporting

**Comment by ThayssaRocha** [comment]
https://openoffice.apache.org/orientation/intro-qa.html 
https://www.debian.org/Bugs/Developer

O que é isso senão um processo de testes?
Eu vou desenhar esses processos. Esses 2 ou 3. E mostro alguma coisa pra vcs na sexta.
Se tiverem outro pra sugerir eu agradeço =)

**Comment by ThayssaRocha** [comment]
@filipesaraiva não to achando uma área de "como contribuir" específica do KDE Plasma. 
Tem essa, que era a que eu vinha analisando e que me parece genérica pra comunidade KDE => https://community.kde.org/Get_Involved/development e que tem bem direitinho o processo de contribuição que me interessa analisar.
Porém, depois achei essa aqui https://community.kde.org/Plasma que tem basicamente coisas sobre a ferramenta e não sobre o processo de interação da comunidade. Sigo considerando a primeira como referência, correto?

**Comment by filipesaraiva** [comment]
Pode continuar seguindo o guia geral do KDE, @ThayssaRocha. :+1:

**Comment by ThayssaRocha** [comment]
[Artigo TESL - Andre e Thayssa.pdf](https://github.com/gustavopinto/tesl/files/3368976/Artigo.TESL.-.Andre.e.Thayssa.pdf)

**Comment by ThayssaRocha** [comment]
@filipesaraiva  e @gustavopinto , também mandei o artigo por e-mail essa madrugada.
Obrigada!
