### ISSUE TITLE
Proposta de Projeto Final - Dupla JOÃO e THIAGO

### ISSUE THREAD

**Issue by lubien** [gustavopinto/tesl#151]
## Dupla

@lubien e @uzumis

## Tipo

Adicionar grande funcionalidade

## Issue(s) Relacionadas

https://github.com/sindresorhus/eslint-plugin-unicorn/issues/238

## Possui PR(s)?

[WIP] https://github.com/sindresorhus/eslint-plugin-unicorn/pull/302

## Sumário

[ESlint](https://eslint.org/) é o linter mais utilizado da comunidade JavaScript. Ele permite a criação de regras usando sua API de plugins.

[xo](https://github.com/xojs/xo) é uma configuração do ESlint bem conhecida (4.5k+ ⭐️). Além de configurar certas regras existentes, ele acrescenta um plugin do mesmo criador para novas funcionalidades, [sindresorhus/eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn).

Em 5 de fevereiro uma regra uma issue para a criação de uma regra nova foi criada. [Rule proposal: Expiring TODO comments](https://github.com/sindresorhus/eslint-plugin-unicorn/issues/238). A discussão se estendeu até 6 de maio mas nenhuma PR apareceu, mesmo com uma pessoa se candidatando.

Em resumo, a regra deixa você adicionar parâmetros em comentários TODO para definir um tempo de vida a ele. Exemplos:

* `TODO [2019-06-31]: fix before submiting` faz com que, a partir do dia 31 de junho de 2019, o linter cause erros na linha do TODO.
* `TODO [engines node>=12]: use module system instead of CommonJS` faz com que caso a biblioteca aumente a versão mínima de suporte de uma [engine](https://docs.npmjs.com/files/package.json#engines) o TODO se torna um erro.

Dentre outras.

Por que? Sendo uma regra opcional, ela é útil para usuários que não querem deixar comentários desse tipo sem uma condição de parada. A documentação está completa dentro da PR ([ler em markdown](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/cd2aecc4395edbdfb492c1f85acc68d577d8fe83/docs/rules/expiring-todo-comments.md)).

## Status

Implementação inicial, mas requer revisão. Atualmente o mantenedor aparenta estar ocupado.

**Comment by gustavopinto** [comment]
Por mim, está OK para uma atividade grande. @filipesaraiva?

**Comment by filipesaraiva** [comment]
Por mim também @gustavopinto. Boa contribuição, @lubien.
