### ISSUE TITLE
Proposta de Projeto Final - Dupla: Reinaldo e Wescley

### ISSUE THREAD

**Issue by wescley** [gustavopinto/tesl#154]
Gustavo @gustavopinto e Filipe @filipesaraiva 

Bom dia!

Segue a proposta de trabalho final para avaliação. :-)

Criar uma [web blog usando as tecnologias Python e MongoDB](https://docs.google.com/document/d/1-gKaedO37KwaNecqbjTn_oSSuCYnOjZPEI8QJtJ_0aY/edit?usp=sharing) no qual seja possível possível exercitar os seguintes conceitos vistos em sala de aula:

1) Documentação de Software Livre 
2) Gerenciamento de Código e Requisitos
3) Métodos Ágeis e Software Livre
4) Testes e Integração Contínua

Ao final podemos elaborar elaborar um relatório descrevendo as experiências e dificuldades percebidas.

Abraços

**Comment by wescley** [comment]
Reinaldo @reinald28 para conhecimento.

**Comment by filipesaraiva** [comment]
Olá @wescley, penso q essa atividade pode valer como duas documentações (2pt) + tradução (1pt), se vc for utilizar alguma tradução de tutorial. O q acha, @gustavopinto?

**Comment by wescley** [comment]
Professor @filipesaraiva 
Bom dia!
Pelo que entendi faria desta forma a pontuação:

1. Atividade Proposta de Projeto Final - **3 pts (dupla)**
2. Reportar Bug - 1pt (2x) - **2pts (individual)**
3. Melhorar documentação - 1 pt (2x) - **2pts (individual)**
4. Realizar tradução - 1 pt (2x) - **2pts (individual)**
-----------------------------------------------------------------------------
O que daria um total de 9ts.
Bem que o sr e o Gustavo @gustavopinto poderiam considerar o valor de **4 pts para a atividade 1**. 
Só pra somar os 10pts. :-)

Reinaldo @reinald28 para conhecimento.

Abraços

**Comment by gustavopinto** [comment]
oi @wescley, 

talvez fosse o caso de fazer uma atividade de documentação/tradução a mais?

**Comment by wescley** [comment]
Professor Gustavo @gustavopinto 

Boa noite!

De acordo!

Então podemos fechar assim:

    1. Atividade Proposta de Projeto Final - 3 pts (dupla)
    2. Reportar Bug - 1pt (2x) - 2pts (individual)
    3. Melhorar documentação - 1 pt (2x) - 2pts (individual)
    4. Realizar tradução - 1 pt (3x) - 3pts (individual)

Desta forma totalizariam os 10pts. :-)

Reinaldo @reinald28 para conhecimento.

Abraços

**Comment by gustavopinto** [comment]
Por mim excelente.

**Comment by wescley** [comment]
Combinado! 👍

**Comment by filipesaraiva** [comment]
Fechado :handshake:

**Comment by reinald28** [comment]
Bom dia @gustavopinto e @filipesaraiva 

Segue como está o andamento do meu relatório final. Para suas opiniões. 

Ainda devo realizar varias atividades no projeto WEB_BLOG que deve cumprir (até passar) o 1 ponto que está faltando até então.

Dese já agradeço a atenção.

@wescley  para conhecimento.

Segue:

# Relatório do Trabalho Final - Reinaldo Cardoso

* Nome completo: Reinaldo Junior Lopes Cardoso
* Nível: Pós-Graduação
* Matrícula: 201920070029
* [Trabalho em Duplas](https://github.com/gustavopinto/tesl/blob/master/duplas/Dupla_Reinaldo_Cardoso_2_Wescley_Fontes.md)

## SUBSEÇÃO DE TAREFA REALIZADA

* Tarefas

| Tarefa                                                      | Pontuação | Máximo | Em dupla? | Quantidade |
|-------------------------------------------------------------|-----------|--------|-----------| -----------|
| Reportar bug                                                | 1 pt      | 2x     | Não       | 1x         |
| Melhorar documentação                                       | 1 pt      | 2x     | Não       | 2x         |
| Realizar tradução                                           | 1 pt      | 2x     | Não       | 0x         |
| Corrigir bug                                                | 3 pt      | ---    | Não       | 1x         |
| Adicionar pequena funcionalidade                            | 3 pt      | ---    | Não       | 1x         |
| Adicionar grande funcionalidade                             | 7 pt      | ---    | Sim       | 0x         |
| Desenvolver estudo original com artigo sobre software livre | 7 pt      | ---    | Sim       | 0x         |
| TOTAL                                                       | ---       | ---    | ---       | 9 Pts      |

### DESCRIÇÃO CURTA DA TAREFA REALIZADA

* Projeto [pokemongovet](https://github.com/pokemongovet) destina-se a fomentar a adoção de animais, carinhosamente apelidados de pokemon.

* Projeto [web_blog](https://github.com/wescley/web_blog) destina-se a colocar em prática os conceitos aprendidos durante a disciplina TESL.

- Reportar bug	1 pt	2x  Qnt 1x
Foi reportado um bug de um link para uma página inválida. [aqui - pokemongovet](https://github.com/pokemongovet/pokemongovet.github.io/issues/78)


- Melhorar documentação	1 pt	2x  Qnt 2x
Foi movido uma nota de explicação, sobre uma polemica que envolvia uma página do projeto, para um arquivo especifico .md fora do código HTML do projeto. [aqui - pokemongovet](https://github.com/pokemongovet/pokemongovet.github.io/pull/88) e [aqui - pokemongovet](https://github.com/pokemongovet/pokemongovet.github.io/pull/87)
Foi intruduzido o trecho: Como contribuir no projeto [aqui - web_blog](https://github.com/wescley/web_blog/pull/2)

- Realizar tradução	1 pt	2x      Qnt 0x


- Corrigir bug	3 pt Qnt 1x
Foi criada uma página para redicecionar o link inválido. O link agora redireciona para uma página espeficica destinada ao proposito. [aqui - pokemongovet](https://github.com/pokemongovet/pokemongovet.github.io/pull/89) e [aqui - pokemongovet](https://github.com/pokemongovet/pokemongovet.github.io/pull/90)


- Adicionar pequena funcionalidade	3 pt    Qnt 1x
Foi criado uma página de contato para o projeto com envio de e-mail. [aqui - pokemongovet](https://github.com/pokemongovet/pokemongovet.github.io/pull/79)

**Comment by wescley** [comment]
[Relatório de experiência da construção de um software livre - Estudo de Caso: Criação de um web blog REST  utilizando as plataformas: python e mongodb](https://docs.google.com/document/d/1-gKaedO37KwaNecqbjTn_oSSuCYnOjZPEI8QJtJ_0aY/edit?usp=sharing)

**Comment by wescley** [comment]
Reinaldo @reinald28 para conhecimento.
