### ISSUE TITLE
Proposta de Projeto Final - Dupla: André Thayssa - Implementação

### ISSUE THREAD

**Issue by AndreMP93** [gustavopinto/tesl#155]
Adicionar algumas funcionalidades no projeto Algorithms (https://github.com/keon/algorithms).
As funcionalidades que seriam adicionadas seriam:

1. No modulo de [grath](https://github.com/keon/algorithms/blob/master/algorithms/graph) seria implementado os  algoritmos:

    - Busca em profundidade; 
    - Busca em profundidade;
    - Verificação de grafo euleriano; 
    - Verificação de pontos de articulação.
    - Algoritmo de Dijkstra

2. Criação do modulo Pattern matching com os algoritmos: 
    - Boyer-Moore-Horspool
    - BMHS
    - ShiftAnd

Melhorar documentação: https://github.com/LazoCoder/Pokemon-Terminal/pull/173
Pequena Funcionalidade: https://github.com/keon/algorithms/pull/510
Tradução: https://github.com/kopa/RunnersField/pull/13

**Comment by gustavopinto** [comment]
Olá, @AndreMP93. 

No caso, seria 5 contribuições pequenas? Acho adequado. Como sugestão, porém, gostaria que houvesse maior diversidade nas contribuições. Por exemplo, poderiam ser feitas 3 implementações pequenas, um report de bug, e uma documentação.

@filipesaraiva?

**Comment by filipesaraiva** [comment]
Acho que você poderia utilizar a disciplina para fazer pelo menos uma contribuição para um projeto de software "de verdade", sem desmerecer a importância didática desse projeto.

Ou tente ao menos realizar outros tipo de contribuições, como o @gustavopinto comentou.
