### ISSUE TITLE
Proposta de projeto final - @cassiobatista

### ISSUE THREAD

**Issue by cassiotbatista** [gustavopinto/tesl#156]
No trabalho final da disciplinas eu pretendo mexer basicamente dois modelos para o framework Hugo de geração de sites estáticos: 
- **Hugo Academic (HA)** (ver [demo](https://themes.gohugo.io/theme/academic/) e [GitHub source](https://github.com/gcushen/hugo-academic) links) 
- **Beautiful Hugo (BH)** (ver [demo](https://themes.gohugo.io/theme/beautifulhugo/) e [GitHub source](https://github.com/halogenica/beautifulhugo) links)

Minha idéia é fazer um mix com algumas contribuições básicas (1 e 2) e outras mais significativas (3 e 4 abaixo) do tipo:
1. [[PR #285 BH](https://github.com/halogenica/beautifulhugo/pull/285)] melhorar documentação. e.g.: como habilitar o multilingual no BH para habilitar o Português? Não há nada falando sobre isso.
2. [[PR #1121 HA](https://github.com/gcushen/hugo-academic/pull/1121)] iniciar tradução: e.g.: o arquivo YAML de configuração em português no HA ainda estava todo em inglês
3. [[PR #1131 HA](https://github.com/gcushen/hugo-academic/pull/1131)] Customizar a interface de compartilhamento de publicações em redes socials do HA (o que é um improvement de algo que já existe, e estava em uma [issue criada pelo próprio desenvolvedor](https://github.com/gcushen/hugo-academic/issues/1108) para ser lançado em versões futuras)
4. [[PR #286 BH](https://github.com/halogenica/beautifulhugo/pull/286)] Criar uma interface para listar publicações no BH (o que não existe e foi sugerido por mim em [uma issue ainda aberta](https://github.com/halogenica/beautifulhugo/issues/283)). Essa contribuição em especial deu mais trabalho porque eu trabalhei num [conversor de BibTeX pra Markdown/YAML em Python](https://github.com/cassiobatista/bib2md) (fiz um fork de um projeto-base já existente) por preguiça de preencher manualmente as informações de todas as minhas publicações, sendo que todas já estavam no arquivo .bib do LaTeX.

Todas as contribuições acima já foram submetidas por mim como PRs, sendo que a 2 e a 3 já foram aceitas. Minha idéia é fechar o projeto com uma quinta e última contribuição de criar uma seção de Membros no Beautiful Hugo, colocando botões para plataformas acadêmicas tipo Research Gate, Lattes, Google Scholar, etc, além de foto dos membros com o plugin [Hugo Easy Gallery](https://github.com/liwenyip/hugo-easy-gallery). O meu interesse é por estar desenvolvendo o "site" do meu grupo de pesquisa com o Hugo: https://ufpafalabrasil.gitlab.io/ :)

**Comment by filipesaraiva** [comment]
Bacana Cássio, boas contribuições. A somatória dá quantos pontos?

**Comment by cassiotbatista** [comment]
oi @filipesaraiva , vou tentar fazer um brief mais atualizado abaixo:

1. :hourglass_flowing_sand: (**1 pt**) [PR #285 BH](https://github.com/halogenica/beautifulhugo/pull/285) documentation: how to enable multilingual on Beautiful Hugo?
2. :heavy_check_mark: (**1 pt**) [PR #1121 HA](https://github.com/gcushen/hugo-academic/pull/1121) translation: i18n YAML for PT_BR on Hugo Academic
3. :heavy_check_mark: (**3 pt**) [PR #1131 HA](https://github.com/gcushen/hugo-academic/pull/1131) small change: customise pub sharing buttons on Hugo Academic
4. :hourglass_flowing_sand: (**7 pt**) [PR #286 BH](https://github.com/halogenica/beautifulhugo/pull/286) e [PR #287 BH](https://github.com/halogenica/beautifulhugo/pull/287) big change when creating two new sections: one for listing publications, and another for listing members of a group (GIFs of the new layouts can be seen at the respective PR pages on both links provided)

Total (a ser avaliado): 12 pontos :)

Notas:
- Sobre o script do BibTeX pra Markdown, eu não submeti PR pro carinha de onde fiz fork porque modifiquei tanto o código que acabei praticamente criando um novo. Mas eu mantive a licença original dele, pelo menos.
- eu abri a [issue #288](https://github.com/halogenica/beautifulhugo/issues/288) no Beautiful Hugo pra adicionar um link clicável no nome dos autores de posts, e resolvi no [PR #289](https://github.com/halogenica/beautifulhugo/pull/289), mas não acho que seja uma contribuição relevante.

**Comment by gustavopinto** [comment]
Muito bom, @cassiobatista !

**Comment by cassiotbatista** [comment]
Eu fiz outra contribuição pra manipular as cores de um mapa em SVG numa biblioteca de visualização em Python chamada [Bokeh](https://bokeh.pydata.org/en/latest/):

![out (1)](https://user-images.githubusercontent.com/2287025/60387971-255fba00-9a81-11e9-9302-d701a996c877.gif)

Dá pra acompanhar a pequena conversa que eu tive com eles [nessa thread do Twitter](https://twitter.com/cassiobatista/status/1144730785263640583).

**Comment by gustavopinto** [comment]
Muito bom @cassiobatista ! Coloca o link desse PR aqui?

**Comment by cassiotbatista** [comment]
oi @gustavopinto , infelizmente eu não abri um PR pra essa contribuição porque os devs me sugeriram fazer com TypeScript e eu fiz só com Python mesmo por pressa/facilidade, portanto não foi nada "profissional". 

Mas eles me convidaram pra escrever alguma coisinha na seção de [showcase do discourse da lib](https://discourse.bokeh.org/c/showcase), o que eu pretendo fazer, mas não a tempo do deadline da disciplina. Comentei sobre a contribuição só pra aumentar minhas chances de não reprovar :) 

![00](https://user-images.githubusercontent.com/2287025/60554087-949d0e80-9d0c-11e9-8fe2-b5360465c65f.png)
