### ISSUE TITLE
Proposta de Projeto Final - Julio Cesar

### ISSUE THREAD

**Issue by juliocesark** [gustavopinto/tesl#157]
Como proposta final para a disciplina, pretendo contribuir com alguns projetos de software livre, através de ações como, melhorar a documentação, traduzir documentação e implementar pequenas funcionalidades. Então, já comecei a trabalhar com essas contribuições e atualmente já criei uns pull-requests sendo que alguns deles já foram aceitos. Pull-requests criados até o momento:

- Tradução da documentação do projeto [BlindChat](https://github.com/mayukh18/BlindChat): [Pull-Request](https://github.com/mayukh18/BlindChat/pull/33)
- Tradução da documentação do projeto [python-blogs](https://github.com/python-gsoc/python-blogs): [Pull-Request](https://github.com/python-gsoc/python-blogs/pull/240)
- Documentação melhorada do projeto [calourada-bootstrap](https://github.com/JonatasFAlves/calourada-bootstrap): [Pull-Request](https://github.com/JonatasFAlves/calourada-bootstrap/pull/1)
- Documentação melhorada do projeto [peludinhos](https://github.com/getacesupa/peludinhos): [Pull-Request](https://github.com/getacesupa/peludinhos/pull/3)
- Pequena funcionalidade referente a redes sociais utilizando bootstrap-social e font-awesome no projeto [calourada-bootstrap](https://github.com/JonatasFAlves/calourada-bootstrap): [Pull-Request](https://github.com/JonatasFAlves/calourada-bootstrap/pull/2)
- Adicionado um novo botão de compartilhar utilizando modal para apresentar os links de compartilhamento referente a redes socias. Projeto [photo-share](https://github.com/JonatasFAlves/photo-share): [Pull-Request HTML](https://github.com/JonatasFAlves/photo-share/pull/1) e [Pull-Request CSS](https://github.com/JonatasFAlves/photo-share/pull/2)

**Comment by gustavopinto** [comment]
Oi @juliocesark, 

as constribuições são interessantes. Minha única ressalva é com relação as contribuições feitas nos repositórios do @JonatasFAlves. Como você pode ver [nesse arquivo](https://github.com/gustavopinto/tesl/blob/master/trabalho-final.md), "Não serão consideradas contribuições para projetos próprios ou de alunos matriculados na disciplina;"

**Comment by juliocesark** [comment]
Professor @gustavopinto, mais o @JonatasFAlves, não está matriculado na disciplina. O que seria os projetos próprios? Achei que fosse um repositório criado por mim.

**Comment by gustavopinto** [comment]
Ah, desculpe. Era outro Jonatas que está matriculado (embora o @JonatasFAlves seja aluno da UFPA).

@filipesaraiva

**Comment by juliocesark** [comment]
Sim, e ele é bem ativo no github com vários repositórios e tem conta PRO. Por isso escolhi alguns dos repositórios dele para as contribuições. Segui direitinho as regras do trabalho, espero que não tenha problema professor, essas contribuições levaram tempo para serem concluídas.

**Comment by filipesaraiva** [comment]
Projetos próprios seriam do próprio aluno. A ideia da disciplina é justamente contribuir com projetos dos outros, tornando as contribuições as mais diversas possíveis. Para a questão específica das contribuições do @juliocesark, sem problemas.

**Comment by gustavopinto** [comment]
Manda bala então, @juliocesark !
