### ISSUE TITLE
EdsonECS e Fábio Pacheco

### ISSUE THREAD

**Issue by EdsonECS** [gustavopinto/tesl#160]
A MEIA IDADE NO MERCADO DE TRABALHO: O DILEMA DO PROFISSIONAL DE MEIA IDADE NA TROCA DO DIVISOR DE ÁGUAS PROFISSIONAIS USANDO SOFTWARES LIVRES.
[Uploading Artigo do Mestrado no Profissional - A MEIA IDADE NO MERCADO DE TRABALHO.pdf…]()

**Comment by EdsonECS** [comment]
Gustavo ou Felipe Gostaria da opinião de vocês neste projeto.

**Comment by gustavopinto** [comment]
@EdsonECS, 

comentários foram enviados por email hoje. Por favor, poste aqui as atualizações.

@fabiomelg, precisamos que você justifique sua participação no projeto.

**Comment by fabiomelg** [comment]
Proposta para o título do artigo no formato SBC, conforme conversado com EdsonCS.
A MEIA IDADE NO MERCADO DE TRABALHO: O DILEMA DO PROFISSIONAL DE MEIA IDADE AGREGANDO DIVISORES DE ÁGUAS PROFISSIONAIS USANDO SOFTWARES LIVRES.
