### ISSUE TITLE
Proposta de Trabalho Final - Dupla: Leonardo e Lucas

### ISSUE THREAD

**Issue by tavareslucas** [gustavopinto/tesl#161]
@gustavopinto @filipesaraiva 
Eu e o @leochrisis estavamos com dificuldades em achar um possível tema para um artigo, e pensamos em fazer o seguinte:
Artigo: Um mapeamento sistemático do uso de OSS/ free software no ensino de programação no brasil
O artigo seria dividido em:
- Introdução
- Trabalhos correlatos
- fundamentação teórica
- metodologia
- resultados obtidos
- conclusões
- referencias

quanto à metodologia, pensamos em utilizar strings de busca (baseadas, também, em trabalhos correlatos) nas seguintes bases: IEEE, ACM, SBIE e CBIE
As principais perguntas do trabalho seriam: 
- Entre os trabalhos encontrados, quantos foram realizados por instituições brasileiras?
- De quais formas os trabalhos coletados trabalham com OSS?
- Entre os trabalhos coletados, quantos utilizam projetos de OSS desenvolvidos por brasileiros, e quais são esses projetos?

Quanto ao restante dos pontos, realizei 2 traduções ( 2 pts), e ainda estou procurando mais uma contribuição de 1 pt.

Qualquer sugestão é bem-vinda.

**Comment by gustavopinto** [comment]
Oi @tavareslucas, 

eu particularmente tenho minhas reservas. 

Apesar do tema ser de meu interesse, eu acredito que seja desafiador fazer esse tipo de trabalho, levando em consideração o tempo de disciplina restante. Em experiência própria (já fiz trabalhos acadêmicos nesse contexto), é um pouco complicado encontrar essas fontes de uso de projetos de software livre em disciplinas. 

Os relatos são esparsos, e muito incipientes. Talvez isso seria mais interessante se você tivesse mais tempo para pensar (1) na questão de pesquisa (que acho que ainda não está muito madura) e (2) como e onde encontrar as fontes (talvez o simples uso da base de dados com palavras genéricas como "open source" e "course"  não seja adequado, pois devem retornar muitos falso positivos). Como resultado, talvez a sua revisão não tenha a profundidade que ela mereça. 

A próxima e última aula será sobre métricas de software. Talvez seja uma boa oportunidade para fazer um estudo. Um exemplo em potencial seria rodar alguma ferramenta que extrai métricas em algum conjunto (centenas ou milhares) de projetos e reportar os achados de forma bem quantitativa. 

O que você acha?

**Comment by tavareslucas** [comment]
@gustavopinto ,

Conversamos com o @filipesaraiva , e ele sugeriu que fizessemos uma análise relacionada às contribuições para as bibliotecas científicas do python, numpy e scipy. O foco seria verificar quais commiters utilizam essas bibliotecas em seus projetos e também contribuem para elas. Seria possível realizar algo do tipo?

**Comment by tavareslucas** [comment]
NVM, fomos com a sua proposta
Rodamos o sonarqube em uns 50 projetos ( ordenador por quantidade de fork, >5000) e iremos entregar uma análise quantitativa dos números retornados pelo software

**Comment by gustavopinto** [comment]
@tavareslucas, interessante. Vejam esse trabalho e usem a mesma abordagem por ele empregada: http://gustavopinto.org/lost+found/icpc2019.pdf
