### ISSUE TITLE
Sugestões de tarefas

### ISSUE THREAD

**Issue by lubien** [gustavopinto/tesl#163]
Assinem o tópico que casso eu encontre mais eu atualizo e adiciono.

Se alguma coisa tiver uma dificuldade/tecnologias diferentes do que reportei, me avisem.

## Bugfixes e Funcionalidades pequenas.

Misturados: Reportar bug, Melhorar documentação, Realizar tradução, Corrigir bug e Adicionar pequena funcionalidade.

[Add eslint 6 to CI #326](https://github.com/sindresorhus/eslint-plugin-unicorn/issues/326)
**Descrição:** configurar a versão 6 do eslint. Atualmente usam a 5.
**Tecnologias:** NodeJS (configuração)
**Dificuldade:** baixa.

[Consider picking files to deploy](https://github.com/pandrRe/Fastable/issues/2)
**Descrição:** configurar lista de arquivos para serem publicados no NPM.
**Tecnologias:** NodeJS (configuração)
**Dificuldade:** baixa.

[Support rewriting animations](https://github.com/trickstival/vue-typing/issues/3)
**Descrição:** Animação de reescrever texto na tela.
**Tecnologias:** VueJS.
**Dificuldade:** baixa.

[Arquivos de Tipo em TypeScript](https://github.com/trickstival/vue-typing/issues/4)
**Descrição:** Adicionar tipagem estática ao repositório.
**Tecnologias:** TypeScript, Vue (básico).
**Dificuldade:** média.

[Gerar Demo com Storybook](https://github.com/trickstival/vue-typing/issues/4)
**Descrição:** Configurar um Storybook para o projeto.
**Tecnologias:** Vue.
**Dificuldade:** média.

[Melhorar documentação do repositório (aprendemos isso na disciplina)](https://github.com/trickstival/vue-typing/issues/4)
**Descrição:** Code of Conduct, CONTRIBUTING...
**Tecnologias:** Markdown.
**Dificuldade:** baixa.

[Header comment with version missing in 2.24 release](https://github.com/moment/moment/issues/5057)
**Descrição:** Cabeçalho faltando.
**Tecnologias:** Texto.
**Dificuldade:** baixa.

[Wrong plural usage for time in PT-BR](https://github.com/moment/moment/issues/3988)
**Descrição:** Correção da versão brasileira (Herbert Richers).
**Tecnologias:** JavaScript (na real, é tradução)
**Dificuldade:** baixa.

["Github"](https://github.com/CiviWiki/OpenCiviWiki)
**Descrição:** escreveram GitHub errado no site.
**Tecnologias:** Texto.
**Dificuldade:** ESSA TÁ DE GRAÇA.

[CiviWiki - Issues para iniciantes em web](https://github.com/CiviWiki/OpenCiviWiki/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22)
**Descrição:** várias issues triviais (como editar um elemento HTML)
**Tecnologias:** HTML e JavaScript
**Dificuldade:** baixa.

[Edit address in edit profile](https://github.com/CiviWiki/OpenCiviWiki/issues/212)
**Descrição:** adicionar campo de editar perfil.
**Tecnologias:** HTML e JavaScript (?).
**Dificuldade:** baixa.

[guppy - Várias issues para iniciantes](https://github.com/joshwcomeau/guppy/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22)
**Descrição:** No geral, modificações na interface web.
**Tecnologias:** React e JavaScript.
**Dificuldade:** baixa a média.

[Document how to intergrate with Doxygen](https://github.com/facebook/docusaurus/issues/943)
**Descrição:** explicar como instalar Doxygen no Docusaurus.
**Tecnologias:** Web.
**Dificuldade:** ?

["up to three parameters" about function that in this challenge takes four parameters](https://github.com/freeCodeCamp/freeCodeCamp/issues/34617)
**Descrição:** Reescrever o texto do desafio.
**Tecnologias:** Texto e saber um pouco de JavaScript.
**Dificuldade:** baixa.

[amphtml - Issues relacionadas a frontend](https://github.com/ampproject/amphtml/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22)
**Descrição:** Várias issues simples sobre frontend especificamente para iniciantes.
**Tecnologias:** HTML, CSS e entender um pouco sobre AMP (é simples, eu prometo).
**Dificuldade:** baixa a média.

## Possíveis funcionalidades grandes.

Confirmem com os professores se realmente valem como "Adicionar grande funcionalidade".

[Account Deletion.](https://github.com/CiviWiki/OpenCiviWiki/issues/227)
**Descrição:** Adicionar a funcionalidade de deletar contas.
**Tecnologias:** HTML e JavaScript.
**Dificuldade:** possivelmente média, mas o mantenedor oferece mentoria no processo.

[Set up continuous integration to run automated tests aganst pull requests](https://github.com/CiviWiki/OpenCiviWiki/issues/146)
**Descrição:** fazer setup de integração contínua (testes já existem).
**Tecnologias:** Integração contínua e um pouco de linha de comando.
**Dificuldade:** (provavelmente) alta.

[Update project to use Python 3](https://github.com/CiviWiki/OpenCiviWiki/issues/18)
**Descrição:** Mudar de python 2.7 para 3.
**Tecnologias:** Python 2.7 e 3.
**Dificuldade:** médio (?).

[Can we make a Website for this?](https://github.com/fossasia/flappy-svg/issues/78)
**Descrição:** Criar um site para o jogo.
**Tecnologias:** Sendo capaz de criar um site estático, tá valendo.
**Dificuldade:** baixa.

**Comment by CaioSR** [comment]
Header comment with version missing in 2.24 release
Descrição: Cabeçalho faltando.
Tecnologias: Texto.
Dificuldade: baixa.

levou o farelo
