### ISSUE TITLE
Proposta de Trabalho Final - Uriel

### ISSUE THREAD

**Issue by urielfcampos** [gustavopinto/tesl#164]
Como trabalho final, estou contribuindo com repositórios open source de acordo com a tabela.
Até agora já fiz :

Proposta de trabalho | Pontuação | Comprovação
------------ | ------------- | ---------------
Pequena funcionalidade | 3.0       | [PR](https://github.com/trickstival/vue-typing/pull/6)
Melhorar Documentação  | 1.0       | [Issue](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/issues/219#issuecomment-506033821), [Wiki deles após sugestão](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/wiki/Compiling-the-Generator)
Grande Funcionalidade  | 7.0       | [PR](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/pull/220)

**Comment by gustavopinto** [comment]
Oi @urielfcampos, 

muito boa as contribuições (com PR aceito 🎉). Sem duvida não é uma contribuição pequena, mas estou na dúvida se é uma contribuição grande..  Pra eu ter uma melhor noção de contribuição grande, é preciso comparar com a contribuição dos demais alunos. 

Minha sugestão é: termine as atividades pendentes enquanto a gente avalia os demais. Enquanto isso, coloque uma tabela com a pontuação pretendida aqui?

**Comment by urielfcampos** [comment]
Olá professor, eu finalizei atividades já, está na PR #189, vou alterar a issue aqui com a tabela.

**Comment by gustavopinto** [comment]
Excelente!
