### ISSUE TITLE
Proposta Trabalho final - Dupla: Ronaldd e Wagner

### ISSUE THREAD

**Issue by wagnernegrao** [gustavopinto/tesl#165]
@gustavopinto  @filipesaraiva 

Eu e o @ronaldpnh estávamos buscando um tema para o artigo e pensamos que em projetos em que a construção do ambiente de desenvolvimento é mais complexa (como em C e C++ por exemplo) talvez possuam uma tendencia menor a atrair contribuidores novatos em comparação a projetos que tenham um processo mais simplificado.

Por exemplo, a construção de projetos em C possui um processo de compilação mais complexo em relação a dependências se comparados a projetos escritos em Python que podem utilizar ferramentas como o `pip` para auxiliar na configuração do ambiente de desenvolvimento.

Nossa ideia é um trabalho que aborde a seguinte questão: **A facilidade de configuração de um ambiente de desenvolvimento influencia na entrada de novos contribuidores?**

Atualmente não sabemos como estruturar essa tema, desta forma gostaríamos desse feedback sobre a viabilidade dessa pesquisa.

O que vocês acham ?

**Comment by gustavopinto** [comment]
Rapaz, é interessante, de fato. Tenho algumas ressalvas... Mas a principal é: da pra fazer até essa sexta?

**Comment by wagnernegrao** [comment]
Creio que não vai da pra fazer até sexta. Vai ser o jetio tentar fazer um a contribuição @ronaldpnh
