### ISSUE TITLE
Proposta Trabalho final - Dupla: Caio e Isaac

### ISSUE THREAD

**Issue by ghost** [gustavopinto/tesl#169]
Como conversado e validado pelo Prof. Filipe, eu, Caio, e o @elgrably pensamos fazer um “artigo” e uma “adição de grande funcionalidade” para o trabalho final em dupla. Segue abaixo a descrição de ambos. 

- Estudo original com o artigo sobre software livre. Título: Mapeamento de Ferramentas e Frameworks de Testes utilizando Mineração de Repositórios no Github.

O artigo seria dividido em:

- Introdução

- Fundamentação teórica
* Mapeamento de Ativos
* Dataset GHTorrent
* Trabalhos Relacionados

- Metodologia do Estudo
* Consulta referentes a Plugins ou Ferramentas de Testes no Repositório
* Consulta referente a quantidade de Watchers nesses projetos.
* Consulta referente a quantidade de Commits nos principais resultados.
* Consulta referente a quantidade de Issues abertas nesses projetos

- Discussão dos resultados obtidos

- Conclusões

- Referências

Será utilizado o Dataset GHTorrent (ghtorrent-bq.ght_2018_04_01) na plataforma Google Cloud para obtenção dos resultados. O interesse para o trabalho é que o aluno @elgrably fez um artigo sobre mapeamento de ativos para Ensino e Treinamento de Testes e os documentos base tinham um período “defasado” como por exemplo o Currículo da SBC (2005), então viu-se a oportunidade de utilizar algo que foi aprendido na disciplina

- Adição de grande funcionalidade. Integração de um novo algoritmo de Aprendizado de Máquina (ML) à biblioteca ML de código aberto Scikit-learn [https://github.com/scikit-learn/scikit-learn](#). O algoritmo é chamado de Sistema de Coordenadas Poligonais, e seu principal objetivo é a visualização de dados em alta dimensionalidade usando redução de dimensionalidade geométrica.

Resumo. A redução de dimensionalidade (DR, do inglês "Dimensionality Reduction") é bastante útil para obtenção de informações relevantes com enfoque no entendimento e insight de dados em alta dimensão. Nossa funcionalidade consiste numa nova abordagem geométrica para DR chamada Sistema de Coordenadas Poligonais (PCS, do inglês “Polygonal Coordinate System”), capaz de representar eficientemente dados multidimensionais em um plano 2D, preservando a estrutura global dos dados. Para este propósito, os dados são representados através de um polígono regular ou interface entre a alta dimensionalidade e os dados bidimensionais. O PCS pode manipular adequadamente grandes quantidades de dados, também conhecidos como Big Data, adotando DR geométrica e incremental de complexidade de tempo linear.

**Comment by filipesaraiva** [comment]
Send bullet galera :+1:

**Comment by CaioMFRodrigues** [comment]
# Relatório do Trabalho Final - Caio e Isaac 

- Nome completo: Caio Marcos Flexa Rodrigues/ Isaac Souza Elgrably
- Nível: Pós-Graduação/ Pós-Graduação 
- Matrícula: 201820080007/ 201820080008
- Trabalho em Duplas: ./duplas/Dupla_Caio_Isaac.md

 ## Adicionar grande funcionalidade
Link: [https://github.com/scikit-learn/scikit-learn/pull/14239](#) 

 ## Estudo original com o artigo sobre software livre
Enviado por email.
