### ISSUE TITLE
Proposta projeto Final - Victor

### ISSUE THREAD

**Issue by Victor-Saldanha** [gustavopinto/tesl#176]
No projeto final foi escolhido o desenvolvimento de um artigo acadêmico e 3 implementações:

- A proposta é implementar uma interoperabilidade de tecnologias distintas. Onde será um sistema de banco de dados Oracle de alta disponibilidade e segurança com RAID nativo , com aplicação de backup com Bácula e integração em nuvem com AWS(Amazon Web Server).
Ps: haverá daemons automatizados em Shell Script, para automatizar algumas tarefas(como integração do BD Oracle com RAID, e aplicação da ferramenta crontab, para configurar o backup de forma pragmática e sistemática do Bácula e o serviço em nuvem da Amazon) (7 pts)

- Tradução de módulos do projeto https://github.com/videolan/vlc (1 pts)

- Tradução de textos para maior acessibilidade no projeto https://github.com/luisivan/QtOctave (1 pts)

- Report de adição de compatibilidade de plugin , no projeto https://github.com/xonotic/xonotic (1 pts)

**Comment by gustavopinto** [comment]
Oi @Victor-Saldanha, 

com relação ao primeiro trabakhio, não me parece que a sugestão feita não se encaixa muito como artigo acadêmico. Um artigo acadêmico parte da premissa de um problema de pesquisa. O seu problema, pelo que eu pude perceber, é mais um problema tecnologico (posso estar enganado). Dessa forma, talvez a descrição da implementação poderia ser feita como um post em um blog. 

Para os demais, você poderia colocar um link para os PRs?

**Comment by Victor-Saldanha** [comment]
Bom dia professor, sobre o primeiro trabalho, até onde sei o artigo acadêmico pode estar nos conceitos de Estudo de Caso, Aplicação de uma solução especifica , ou atualização/recomposição de uma tecnologia anteriormente implementada em algum contexto  ....bom , no caso, o senhor vai aceitar a entrega desse artigo para sua triagem? ou em paralelo a sua indicação (post em blog) ,o senhor gostaria de me aconselhar, a adaptar esse artigo proposto ou modifica-lo ... enfim ...e ok, irei postar as PR's.
