### ISSUE TITLE
Proposta de Trabalho Final - Caio Shimada

### ISSUE THREAD

**Issue by CaioSR** [gustavopinto/tesl#185]
Para o trabalho final estou contribuindo com outros projetos como descrito no documento de trabalho final.

Até agora:

Documentação: Realizei um pull-request para adicionar um header com a versão e outras informações em um arquivo como pedido em uma issue -> [PR](https://github.com/moment/moment/pull/5153)

Correção de Bug: Em um projeto, o teste automático da página não conseguia acessar um campo específico da página já que ele não possuía ID, logo, adicionei o ID nesse campo dinâmico como solicitado em uma issue.  -> [PR](https://github.com/CiviWiki/OpenCiviWiki/pull/537)

Correção de Bug: Altera de maíusculo para minúsculo os nomes do meses em pt e pt_BR -> [PR](https://github.com/moment/moment/pull/5158)

Por enquanto é isso.

**Comment by gustavopinto** [comment]
Muito legal, so far, @CaioSR (com PR aceito! 🎉). Faz uma tabela com o somatório? E as demais atividades? Para sugestões de outras atividades, veja: https://github.com/gustavopinto/tesl/issues/163

**Comment by CaioSR** [comment]
Temporário (talvez). @gustavopinto 

| Tarefa | Pontuação | Repetição |
| --- | --- | --- |
| Melhorar documentação | 1 pt | 1x |
| Corrigir bug | 3 pts | 2x |

| Pontuação Total | 7 pts |
| --- | --- |
