### ISSUE TITLE
Proposta de Trabalho Final - Victor Ferreira

### ISSUE THREAD

**Issue by VictorBSI** [gustavopinto/tesl#187]
Para o trabalho final, fiz pull requests para corrigir bugs, adicionar pequena funcionalidade, realizei duas traduções e reportei dois bugs. Todas as contribuições já foram feitas. Segue abaixo as contribuições já desenvolvidas:

* Reportar Bug

1. Foi aberta uma [issue](https://github.com/glugmvit/glugmvit.github.io/issues/53) para reportar um bug no ícone do Twitter dos autores, pois não aparecia corretamente.
2. Foi aberta uma [issue](https://github.com/phucuongit/vaibekum_pro_1/issues/1) para reportar um bug nos botões sociais, pois eles não redirecionavam para as respectivas redes sociais indicadas.

* Realizar tradução

1. Foi feito o [pull request](https://github.com/w3c/wai-intro-accessibility/pull/43) para a tradução da página principal deste [projeto](https://github.com/w3c/wai-intro-accessibility).
2. Foi feito o [pull request](https://github.com/centosadmin/redmine_recurring_tasks/pull/57) para a tradução do módulo de strings deste [projeto](https://github.com/centosadmin/redmine_recurring_tasks).

* Adicionar pequena funcionalidade

1. Foi feito o [pull request](https://github.com/glugmvit/glugmvit.github.io/pull/51) para a adição da pequena funcionalidade requisitada na seguinte [issue](https://github.com/glugmvit/glugmvit.github.io/issues/50), na qual o colaborador pediu para adiconar um botão scroll para voltar para o topo de uma página.

* Corrigir Bug

1. Foi feito o [pull request](https://github.com/glugmvit/glugmvit.github.io/pull/52) para a correção do bug informado na seguinte [issue](https://github.com/glugmvit/glugmvit.github.io/issues/36), na qual o colaborador pedia para corrigir o alinhamento da descrição dos autores com os seus respectivos nomes.

**Comment by gustavopinto** [comment]
Oi @VictorBSI, interessante as contribuições. 

Você poderia fazer uma tabela com a pontuação pretendida? 

Para os PRs que foram feitos comentário (eg https://github.com/w3c/wai-intro-accessibility/pull/43), você poderia continuar a interação?

**Comment by VictorBSI** [comment]
Aqui a tabela professor @gustavopinto 

| Tarefas realizadas               | Pontuação pretendida | Número de repetições |
|----------------------------------|:--------------------:|:--------------------:|
| Reportar bug                     |        1 pt          |          2x          |
| Realizar tradução                |        1 pt          |          2x          |
| Corrigir bug                     |        3 pt          |         1x          |
| Adicionar pequena funcionalidade |        3 pt          |         1x          |


| Pontuação Total pretendida       |                     10 pts                  |
|----------------------------------|---------------------------------------------|
