### ISSUE TITLE
Local de hospedagem do projeto

### ISSUE THREAD

**Issue by marlluslustosa** [gustavopinto/tesl#231]
Olá. Gostei muito da iniciativa de elaboração do plano para uma disciplina especialmente voltada ao Software Livre.

A primeira sugestão que tenho a fazer, inicialmente, seria a disponibilidade do projeto em um repositório de código licenciado com siglas que atendam às especificações da definição do Software Livre (https://www.gnu.org/philosophy/free-sw.html). 
As sugestões seriam:
https://notabug.org/
https://savannah.gnu.org

Estas sugestões vieram do grupo 'Software Livre #ultraGNU', do telegram: https://web.telegram.org/#/im?p=@ultragnus

Mais uma vez, parabéns pela iniciativa.

**Comment by gustavopinto** [comment]
Obrigado, @marlluslustosa. 

Sem dúvida concordo que o GitHub talvez não seja o melhor local para hospedar um site de disciplina de software livre, filosoficamente falando. No entanto, educaionalmente falando, talvez seja uma solução adequada, já que minimiza a barreira de entrada dos alunos (muitos deles já estão habituados com a interface e com o pipeline). São pontos para se ponderar.

No futuro, é provável que a gente revisite a escolha de usar  GitHub para esse fim. A sugestão de fato faz todo sentido.

\cc @filipesaraiva

**Comment by filipesaraiva** [comment]
Fala @marlluslustosa, e aê! Blz?

De fato quando pensamos a disciplina optamos pelo Github para que a entrada dos que já usam a ferramenta fosse simples e que eles próprios pudessem auxiliar os que ainda não usam.

Mas o grupo de pesquisa Centro de Competência em Software Livre da UFPA tem um namespace no [Gitlab](https://gitlab.com/ccsl-ufpa/), que é software livre e pode vir a ser a opção para a próxima vez que a disciplina for ministrada.

**Comment by filipesaraiva** [comment]
Ah @marlluslustosa, esqueci de comentar mas na época que configuramos esse Github fiz também um mirror dele no [Gitlab do grupo de pesquisa](https://gitlab.com/ccsl-ufpa/tesl).

Certamente adotaremos esse repositório na próxima vez que ofertarmos a disciplina.

**Comment by marlluslustosa** [comment]
E aí @filipesaraiva! td bem, meu caro!
Obrigado pelas respostas, @filipesaraiva e @gustavopinto.

Complementando o que vocês falaram, deixo aqui links de uma leitura que recomendo bastante sobre os critérios de repositórios éticos, defendidos pela GNU.
https://www.gnu.org/software/repo-criteria.html
https://www.gnu.org/software/repo-criteria-evaluation.html

No mais, agradeço novamente a iniciativa!
:)
